# Generated by Django 4.0.3 on 2022-03-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pav',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
