export const random = (min, max) => {
    //min & max included
    return Math.floor(Math.random() * (max - min + 1) + min);
}

export const generateInput = () => {
    const rands = [];
    for (let i = 0; i < 3; i++){
        rands.push(random(1, 10));
    }
    return rands;
}

const randomNames = [
    'Nyla Martin',
    'Isaac Hicks',
    'Toby Phelps',
    'Riley Carrillo',
    'Marlon Parker',
    'Arielle Tucker',
    'Desiree Gregory',
    'Jamie Bartlett',
    'Jefferson Santana',
    'Brandon Zamora',
    'Lillianna David',
    'Kamren Cruz',
    'Camryn Bowman',
    'Maxim Wilkins',
    'Lindsey Keller',
    'Cannon Dixon',
    'Maximilian Kaufman',
    'Litzy Kaufman',
    'Cullen Riddle',
    'Lesly Burns',
    'Kenyon Decker',
    'Micah Caldwell',
    'Myles Rich',
    'Darnell Moss',
    'Nola Randall',
    'Lamont Brennan',
    'Cody Mercado',
    'Esmeralda Malone',
    'Roderick Richmond',
    'Atticus Edwards',
    'Leroy Madden',
    'Frankie Nolan',
    'Jesse Church',
    'Carlie Torres',
    'Alec Snow',
    'Bruno Wilkins',
    'Leonidas Mooney',
    'Johanna Watts',
    'Kaylin Odonnell',
    'Lamont Mclean',
    'Margaret Washington',
    'Alondra Santiago',
    'Tatiana Mclean',
    'Brooklyn Walsh',
    'Yael Phelps',
    'Kylie Hurst',
    'Kolton Singh',
    'Sydney Decker',
    'Connor Higgins',
    'Romeo Bowman',
    'Luka Miles',
    'Donovan Mcdowell',
    'Eliza Garcia',
    'Priscilla Mullen',
    'Ingrid Hubbard',
    'Semaj English',
    'Eileen Bradford',
    'Maddox Klein',
    'Talon Randolph',
    'Aimee Byrd',
    'Keyla Acevedo',
    'Zechariah Choi',
    'Caroline Burns',
    'Melanie Stone',
    'Vaughn Holloway',
    'Tristen Odonnell',
    'Bruce Sparks',
    'Kassidy Wells',
    'Alexis Riggs',
    'Noah Ibarra',
    'Amiyah Landry',
    'Gael Briggs',
    'Ace Charles',
    'Kaia Good',
    'Gideon Stevens',
    'Moses Hoover',
    'Ralph Neal',
    'Melany Davies',
    'Melany Henderson',
    'Dalia Ramsey',
    'Marquise Moody',
    'Mathew Holt',
    'Kenny Forbes',
    'Kylie Barton',
    'Leia Mathews',
    'Dane Delgado',
    'Marlene Jarvis',
    'Azul Myers',
    'Malia Floyd',
    'Marina Sharp',
    'Zaire Orozco',
    'Frances Randolph',
    'Jada Klein',
    'Trevon Pope',
    'Audrey Smith',
    'Kelsey Watson',
    'Fabian Bridges',
    'Alani Mcintyre',
    'Francisco Wagner',
    'Essence Acosta'
];

const randomOffices = [
    "Prime Minister's Office",
    "Prime Minister's Office",
    'Agriculture and Rural Development',
    'Aliyah and Integration',
    'Communications',
    'Culture and Sports',
    'Defense',
    'Development of the Negev and the Galilee',
    'Economy and Industry',
    'Education',
    'Energy',
    'Environmental Protection',
    'Finance',
    'Foreign Affairs',
    'Health',
    'Interior',
    'Jerusalem And Heritage',
    'Justice',
    'Public Security',
    'Religious Services',
    'Science and Technology',
    'Social Equality',
    'Welfare and Social Affairs',
    'Tourism'
];

export const generateRandomOfficeName = () => {
    const idx = random(0, 24);
    const name = randomOffices[idx];
    return name;
}