# Generated by Django 4.0.3 on 2022-04-14 15:18

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pav_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PavFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=api.models.upload_file)),
            ],
        ),
    ]
